---
- name: install docker and required components
  hosts: all
  tasks:
   - name: install python pip
     apt: 
      name: python3-pip
      state: present
      update_cache: yes
   - name: Download the docker shell script
     shell: curl -fsSL https://get.docker.com -o get-docker.sh
     shell: sh get-docker.sh
   - name: install docker-py
     shell: pip3 install docker-py    
...        
