- name: Error Handling or exception handling
  hosts: all 
  tasks:
   - block:
      - name: install tomcat8
        apt:
         name: tomcat8
         state: present
         update_cache: yes
     rescue:
      - name: install tomcat9
        apt:
         name: tomcat9
         state: absent
         update_cache: yes
     always:
      - name: Display output 
        debug:
         msg: Tomcat setup succesfull 
...           
