---
- name: install s/w applications
  hosts: all
  tasks: 
   - name: install s/w
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"

     with_items:
      - {a: tree, b: present, c: no}
      - {a: openjdk-8-jdk, b: absent, c: no}
      - {a: maven, b: absent, c: no}
...        
