---
- name: Create a user 
  hosts: 10.0.0.6
  tasks:
    - name: creating a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
...          
       
