---
- name: configuring tomcat
  hosts: all
  tasks:
   - name: install tomcat9
     apt:
       name: tomcat9
       state: present
       update_cache: yes
   - name: copy the tomcat-users.xml file
     copy:
       src: tomcat-users.xml
       dest: etc/tomcat9/
   - name: change the port to 9090
     replace:
       regexp: 8080
       replace: 9090
       path: /etc/tomcat9/server.xml
   - name: Restart tomcat
     service:
       name: tomcat9
       state: restarted
   - name: Pause for 1min
     pause:
       minutes: 1
   - name: check tomcat response on server1
     uri:
       url: http://10.0.0.6:9090
       status_code: 200
   - name: check tomcat response on server2
     uri:
       url: http://10.0.0.11:9090
       status_code: 200
...         
